# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Raagi 不是拉雞
tagline:          '祈禱不會變成廢文倉庫的地方'
description:      'Security Research Readings and Drafts of My Research'
url:              https://nashi5566.github.io              
baseurl:           

author:
  name:           'Raagi'
  url:            https://twitter.com/raagi0711

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nashi5566
